clean:
	rm -rf *.aux
	rm -rf *.bbl
	rm -rf *.bcf
	rm -rf *.blg
	rm -rf *.fdb_latexmk
	rm -rf *.fls
	rm -rf *.log
	rm -rf *.nav
	rm -rf *.out
	rm -rf *.run.xml
	rm -rf *.snm
	rm -rf *.synctex.gz
	rm -rf *.toc